In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
datasaet_df = pd.read_csv("D:\\pysparkProject\\pythonMachineLearning\\Data.csv")
print(datasaet_df.head())

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes


In [4]:
datasaet_cols_reqd_df = datasaet_df.iloc[:, :-1]
print(datasaet_cols_reqd_df.head())
datasaet_cols_independent_var = datasaet_cols_reqd_df.values
print(datasaet_cols_independent_var)

   Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [5]:
"""selecting  only the dependednt variable"""
dependent_var_df = datasaet_df.iloc[:,-1]
print(dependent_var_df.head())
datasaet_cols_dependent_var = dependent_var_df.values
print(datasaet_cols_dependent_var)

0     No
1    Yes
2     No
3     No
4    Yes
Name: Purchased, dtype: object
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [6]:
"""replace missing data with the average of that column using scikit learn library."""
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy="mean")
imputer.fit(datasaet_cols_independent_var[:,1:3]) ## it takes only numerical values
datasaet_cols_independent_var[:,1:3]= imputer.transform(datasaet_cols_independent_var[:,1:3])
print(datasaet_cols_independent_var)



[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [7]:
###Encoding independent Variable
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
### except the columns for which one hot encoding is implemented other columns will have no change - remainder='passthrough'
###  [0] column changes will be done
## encoding is OneHotEncoder
ct= ColumnTransformer(transformers= [('encoder', OneHotEncoder(), [0])], remainder='passthrough')
datasaet_cols_independent_var = np.array(ct.fit_transform(datasaet_cols_independent_var))
print(datasaet_cols_independent_var)


[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [8]:
###Encoding dependent Variable using LabelEncoder
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
datasaet_cols_dependent_var =le.fit_transform(datasaet_cols_dependent_var)
print(datasaet_cols_dependent_var)

[0 1 0 0 1 1 0 1 0 1]


In [9]:
X = datasaet_cols_independent_var
y = datasaet_cols_dependent_var

In [13]:
# splitting the data into train and test split ratio 0.8, 0.2
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y ,test_size = 0.2,random_state= 1)
print(f"X_train- {X_train}")
print(f"X_test- {X_test}")
print(f"y_train- {y_train}")
print(f"y_test- {y_test}")

X_train- [[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]
X_test- [[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]
y_train- [0 1 0 0 1 1 0 1]
y_test- [0 1]


In [ ]:
# Feature Scaling
